CREATE TABLE users (
  uid VARCHAR(255) NOT NULL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  nickname VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  role VARCHAR(255),
  password VARCHAR(255) NOT NULL,
  department VARCHAR(255)
);
